services:
  - type: web
    name: pdf-llm-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    plan: free
    region: oregon
    branch: main
    rootDir: .
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PORT
        generateValue: true
    healthCheckPath: /health